name: TimeManagement
main: Main.TimeManagement
version: 1.0
api-version: 1.13
depend: []
commands:
  totaltime:
    description: get the total time played
    permission: time.total
    permissions: []
    permission-message: You need time.total to use this.
    usage: "Usage: /totaltime"
  test:
    description: test the data inserts and requests
    permission: time.test
    permissions: []
    permission-message: You need time.test to use this.
    usage: "Usage: /test"
